GET http://localhost:3333/users HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOiJmOTI0ZGVkNC1lZjU3LTQ2MmEtOTk1NC00NzFmNTdmYzU4MjIiLCJuYW1lIjoiYWRtaW4zIiwiZW1haWwiOiJhZG1pbjNAZW1haWwuY29tIiwiaWF0IjoxNzE0NjIxMTk4LCJleHAiOjE3MTQ2MjQ3OTh9.6TI-7OU08UM7xg45ckRzsfTmt3V5lSJAgMMoatnmSPI