GET http://localhost:3333/users HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOiJmOTI0ZGVkNC1lZjU3LTQ2MmEtOTk1NC00NzFmNTdmYzU4MjIiLCJuYW1lIjoiYWRtaW4zIGF0dWFsaXphZG8iLCJlbWFpbCI6ImFkbWluM0BlbWFpbC5jb20iLCJpYXQiOjE3MTUwODcxODEsImV4cCI6MTcxNTA5MDc4MX0.jocR2R0p0b2xH4GDt9wV3wNWcSJL5DtR9mAs9wk447Y