PUT http://localhost:3333/user/update/ HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOiJmOTI0ZGVkNC1lZjU3LTQ2MmEtOTk1NC00NzFmNTdmYzU4MjIiLCJuYW1lIjoiYWRtaW4zIiwiZW1haWwiOiJhZG1pbjNAZW1haWwuY29tIiwiaWF0IjoxNzE1MDE5MTY5LCJleHAiOjE3MTUwMjI3Njl9.BY6rOXAhFLXMR5tfrrgDZNDkH2cc_N_5M60vX9cZIek

{
    "name": "admin3 atualizado"
}