DELETE  http://localhost:3333/user/delete/359cea07-7230-4112-9596-1e6938c47bf8 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOiJmOTI0ZGVkNC1lZjU3LTQ2MmEtOTk1NC00NzFmNTdmYzU4MjIiLCJuYW1lIjoiYWRtaW4zIGF0dWFsaXphZG8iLCJlbWFpbCI6ImFkbWluM0BlbWFpbC5jb20iLCJpYXQiOjE3MTUwMjY3MjQsImV4cCI6MTcxNTAzMDMyNH0.t4e_BxpIykLTAwpAv6r8IWxLnLkE4VsBoAMK25-radg