DELETE  http://localhost:3333/message/delete/e8920ee2-a563-49ee-b79a-513a85cc6c9e HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOiJmOTI0ZGVkNC1lZjU3LTQ2MmEtOTk1NC00NzFmNTdmYzU4MjIiLCJuYW1lIjoiYWRtaW4zIiwiZW1haWwiOiJhZG1pbjNAZW1haWwuY29tIiwiaWF0IjoxNzE0NjUzNDQ1LCJleHAiOjE3MTQ2NTcwNDV9.k9LJ9kQ1JeivCPDTpQk11Fw_VA0X3OyWHQpdzu27Vxo

{
    "idUser": "f924ded4-ef57-462a-9954-471f57fc5822"
}